name: 1 - Orchestrator
on:
  workflow_dispatch:
    
  push:
    branches:
      - dev
jobs:
  Orchestrator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: my-event