name: '1 - Usage of repository-dispatch GitHub Action'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: my-event