name: 1 - Orchestrator
on:
  workflow_dispatch:
    
  push:
    branches:
      - main
jobs:
  reusable-workflow:
    uses: andretiagoss/ngrx_crud/tree/main/.github/workflows/reusable-workflow.yml
    with:
      branch: ${{ github.ref_name }}

  Orchestrator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        repository: ${{ github.repository }}
        event-type: my-event