name: 2 - Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]

permission:
  id-token: write
  contents: read
 
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}