name: Reusable Build and Test

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo branch ${{ inputs.branch }}