name: Reusable Workflow Dispatched

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        type: string

jobs:
  reusable:
    runs-on: ubuntu-latest

    steps:
      - run: echo branch ${{ inputs.branch }}